In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_train = pd.read_csv('InsuranceDataset.csv')

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 21 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1200000 non-null  int64
 1   Age                   1181295 non-null  float64
 2   Gender                1200000 non-null  object
 3   Annual Income         1155051 non-null  float64
 4   Marital Status        1181471 non-null  object
 5   Number of Dependents  1090328 non-null  float64
 6   Education Level       1200000 non-null  object
 7   Occupation            841925 non-null   object
 8   Health Score          1125924 non-null  float64
 9   Location              1200000 non-null  object
 10  Policy Type           1200000 non-null  object
 11  Previous Claims       835971 non-null   float64
 12  Vehicle Age           1199994 non-null  float64
 13  Credit Score          1062118 non-null  float64
 14  Insurance Duration    1199999 non-null  float64
 15  Policy Start Date     1200000 non-null  object
 16  Customer Feedback     1122176 non-null  object
 17  Smoking Status        1200000 non-null  object
 18  Exercise Frequency    1200000 non-null  object
 19  Property Type         1200000 non-null  object
 20  Premium Amount        1200000 non-null  float64
dtypes: float64(9), int64(1), object(11)
memory usage: 192.3+ MB

In [ ]:
df_train = df_train.sample(70000, random_state=42)

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   id                    800000 non-null  int64
 1   Age                   787511 non-null  float64
 2   Gender                800000 non-null  object
 3   Annual Income         770140 non-null  float64
 4   Marital Status        787664 non-null  object
 5   Number of Dependents  726870 non-null  float64
 6   Education Level       800000 non-null  object
 7   Occupation            560875 non-null  object
 8   Health Score          750551 non-null  float64
 9   Location              800000 non-null  object
 10  Policy Type           800000 non-null  object
 11  Previous Claims       557198 non-null  float64
 12  Vehicle Age           799997 non-null  float64
 13  Credit Score          708549 non-null  float64
 14  Insurance Duration    799998 non-null  float64
 15  Policy Start Date     800000 non-null  object
 16  Customer Feedback     747724 non-null  object
 17  Smoking Status        800000 non-null  object
 18  Exercise Frequency    800000 non-null  object
 19  Property Type         800000 non-null  object
dtypes: float64(8), int64(1), object(11)
memory usage: 122.1+ MB

In [ ]:
df_test = df_test.sample(30000, random_state=42)

In [ ]:
df_train.drop(columns = ['id', 'Policy Start Date'], axis=1, inplace=True)
df_test.drop(columns = ['id', 'Policy Start Date'], axis=1, inplace=True)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70000 entries, 372605 to 949825
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   68923 non-null  float64
 1   Gender                70000 non-null  object
 2   Annual Income         67358 non-null  float64
 3   Marital Status        68901 non-null  object
 4   Number of Dependents  63755 non-null  float64
 5   Education Level       70000 non-null  object
 6   Occupation            49237 non-null  object
 7   Health Score          65788 non-null  float64
 8   Location              70000 non-null  object
 9   Policy Type           70000 non-null  object
 10  Previous Claims       48908 non-null  float64
 11  Vehicle Age           70000 non-null  float64
 12  Credit Score          61992 non-null  float64
 13  Insurance Duration    70000 non-null  float64
 14  Customer Feedback     65395 non-null  object
 15  Smoking Status        70000 non-null  object
 16  Exercise Frequency    70000 non-null  object
 17  Property Type         70000 non-null  object
 18  Premium Amount        70000 non-null  float64
dtypes: float64(9), object(10)
memory usage: 10.7+ MB

In [ ]:
df_train.head()

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
372605,52.0,Female,5538.0,Married,NaN,Master's,Employed,8.093145,Rural,Basic,0.0,18.0,497.0,3.0,Average,No,Weekly,Apartment,2742.0
551204,60.0,Female,39711.0,Married,4.0,Bachelor's,Employed,NaN,Suburban,Comprehensive,0.0,3.0,340.0,3.0,Poor,No,Weekly,Apartment,1347.0
240320,58.0,Female,2364.0,Married,2.0,Bachelor's,NaN,34.452482,Urban,Comprehensive,2.0,19.0,NaN,7.0,Poor,No,Monthly,House,2196.0
1047361,39.0,Male,9094.0,Divorced,0.0,Bachelor's,NaN,26.241661,Rural,Basic,1.0,17.0,761.0,5.0,Poor,Yes,Rarely,Condo,684.0
555362,47.0,Male,43189.0,Divorced,NaN,PhD,NaN,26.691921,Suburban,Comprehensive,1.0,4.0,319.0,4.0,Poor,Yes,Weekly,Apartment,1714.0

In [ ]:
df_train[df_train['Occupation'].isna()]

,Age,Gender,Annual Income,Marital Status,Number of Dependents,Education Level,Occupation,Health Score,Location,Policy Type,Previous Claims,Vehicle Age,Credit Score,Insurance Duration,Customer Feedback,Smoking Status,Exercise Frequency,Property Type,Premium Amount
240320,58.0,Female,2364.0,Married,2.0,Bachelor's,NaN,34.452482,Urban,Comprehensive,2.0,19.0,NaN,7.0,Poor,No,Monthly,House,2196.0
1047361,39.0,Male,9094.0,Divorced,0.0,Bachelor's,NaN,26.241661,Rural,Basic,1.0,17.0,761.0,5.0,Poor,Yes,Rarely,Condo,684.0
555362,47.0,Male,43189.0,Divorced,NaN,PhD,NaN,26.691921,Suburban,Comprehensive,1.0,4.0,319.0,4.0,Poor,Yes,Weekly,Apartment,1714.0
886200,NaN,Female,34363.0,Single,2.0,Bachelor's,NaN,16.322329,Urban,Premium,0.0,11.0,NaN,7.0,Good,Yes,Monthly,Condo,1604.0
184524,48.0,Female,15438.0,Single,4.0,PhD,NaN,37.017069,Urban,Comprehensive,0.0,1.0,498.0,3.0,Poor,Yes,Rarely,Apartment,1641.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083738,18.0,Female,9930.0,Single,2.0,PhD,NaN,18.670037,Rural,Basic,1.0,16.0,553.0,9.0,Good,Yes,Weekly,House,262.0
772144,40.0,Female,25380.0,Single,3.0,Master's,NaN,27.125439,Rural,Comprehensive,1.0,17.0,NaN,9.0,Poor,Yes,Weekly,Condo,132.0
393367,38.0,Male,44284.0,Single,2.0,High School,NaN,28.964504,Rural,Premium,NaN,4.0,632.0,6.0,Average,No,Daily,House,814.0
216597,38.0,Male,937.0,Divorced,3.0,Master's,NaN,35.619291,Urban,Comprehensive,1.0,12.0,489.0,4.0,Good,Yes,Rarely,Apartment,955.0
460827,43.0,Male,7092.0,Divorced,2.0,Bachelor's,NaN,47.469027,Rural,Basic,NaN,12.0,439.0,1.0,Average,No,Monthly,Condo,123.0

In [ ]:
df_train_num = df_train.select_dtypes(include = ['int64', 'float64'])
df_train_cat = df_train.select_dtypes(include = ['object'])
df_train_num_cols = df_train_num.drop(columns = 'Premium Amount', axis = 1).columns
df_train_cat_cols = df_train_cat.drop(columns = 'Occupation', axis = 1).columns
extra_cols = ['Occupation']

In [ ]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

def log_transform(X):
    X = np.log(X + 1)
    return X

df_num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = 'median')),
    ('scale', StandardScaler())
])


df_cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = 'most_frequent')),
    ('onehot', OneHotEncoder())
])


df_extra_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = 'constant', fill_value = 'x')),
    ('onehot', OneHotEncoder())
])


transformer = ColumnTransformer([
    ('num', df_num_pipeline, df_train_num_cols),
    ('cat', df_cat_pipeline, df_train_cat_cols),
    ('extra', df_extra_pipeline, extra_cols)
], remainder = 'passthrough')

X_train = pd.DataFrame(transformer.fit_transform(df_train.drop(columns = 'Premium Amount', axis = 1)), columns = transformer.get_feature_names_out())
X_test = pd.DataFrame(transformer.transform(df_test), columns = transformer.get_feature_names_out())

In [ ]:
y_train = df_train['Premium Amount']

In [ ]:
X_train.corrwith(y_train).sort_values(ascending = False)

num__Age                            0.039608
cat__Property Type_Condo            0.027783
cat__Gender_Male                    0.025041
cat__Policy Type_Comprehensive      0.024444
num__Insurance Duration             0.018258
cat__Education Level_High School    0.016675
extra__Occupation_x                 0.015518
cat__Marital Status_Married         0.015285
cat__Location_Urban                 0.013597
cat__Exercise Frequency_Daily       0.012767
cat__Location_Suburban              0.011032
cat__Smoking Status_No              0.006858
num__Number of Dependents           0.006583
extra__Occupation_Employed          0.005042
cat__Exercise Frequency_Weekly      0.002456
cat__Customer Feedback_Average      0.002073
cat__Customer Feedback_Good         0.001608
cat__Marital Status_Single          0.001296
cat__Education Level_Bachelor's     0.000591
num__Vehicle Age                    0.000366
extra__Occupation_Self-Employed    -0.000598
cat__Education Level_PhD           -0.002036
num__Credit Score                  -0.002466
cat__Customer Feedback_Poor        -0.003712
cat__Exercise Frequency_Monthly    -0.004438
cat__Smoking Status_Yes            -0.006858
cat__Policy Type_Premium           -0.007119
num__Health Score                  -0.008524
cat__Exercise Frequency_Rarely     -0.010653
cat__Property Type_Apartment       -0.010791
cat__Education Level_Master's      -0.014988
cat__Marital Status_Divorced       -0.016872
cat__Property Type_House           -0.017009
cat__Policy Type_Basic             -0.017422
extra__Occupation_Unemployed       -0.021615
num__Annual Income                 -0.024297
cat__Location_Rural                -0.024921
cat__Gender_Female                 -0.025041
num__Previous Claims               -0.030784
dtype: float64

In [ ]:
import tensorflow as tf

model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape = (X_train.shape[1],)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dropout(rate=0.2),
    tf.keras.layers.Dense(100, activation = 'leaky_relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(100, activation = 'relu'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(1, activation = 'linear')
])

optimizer = tf.keras.optimizers.AdamW(learning_rate=0.001, beta_1=0.9, beta_2=0.999, weight_decay=1e-5)
model.compile(loss = 'mean_absolute_error', optimizer = optimizer, metrics = ['mean_absolute_error'])

In [ ]:
history = model.fit(X_train, y_train, epochs = 25, validation_split = 0.2)

Epoch 1/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - loss: 1032.7142 - mean_absolute_error: 1032.7142 - val_loss: 692.8164 - val_mean_absolute_error: 692.8164
Epoch 2/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 656.0679 - mean_absolute_error: 656.0679 - val_loss: 638.8696 - val_mean_absolute_error: 638.8696
Epoch 3/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - loss: 635.1501 - mean_absolute_error: 635.1501 - val_loss: 638.3242 - val_mean_absolute_error: 638.3242
Epoch 4/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 637.3214 - mean_absolute_error: 637.3214 - val_loss: 638.0179 - val_mean_absolute_error: 638.0179
Epoch 5/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 634.1590 - mean_absolute_error: 634.1590 - val_loss: 637.5408 - val_mean_absolute_error: 637.5408
Epoch 6/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 632.1859 - mean_absolute_error: 632.1859 - val_loss: 637.2258 - val_mean_absolute_error: 637.2258
Epoch 7/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 633.4437 - mean_absolute_error: 633.4437 - val_loss: 637.2629 - val_mean_absolute_error: 637.2629
Epoch 8/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 632.3298 - mean_absolute_error: 632.3298 - val_loss: 636.7732 - val_mean_absolute_error: 636.7732
Epoch 9/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 633.3886 - mean_absolute_error: 633.3886 - val_loss: 636.6400 - val_mean_absolute_error: 636.6400
Epoch 10/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 635.0817 - mean_absolute_error: 635.0817 - val_loss: 636.7446 - val_mean_absolute_error: 636.7446
Epoch 11/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - loss: 632.7704 - mean_absolute_error: 632.7704 - val_loss: 637.2435 - val_mean_absolute_error: 637.2435
Epoch 12/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 637.1052 - mean_absolute_error: 637.1052 - val_loss: 636.6956 - val_mean_absolute_error: 636.6956
Epoch 13/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 635.4124 - mean_absolute_error: 635.4124 - val_loss: 636.4745 - val_mean_absolute_error: 636.4745
Epoch 14/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 630.8658 - mean_absolute_error: 630.8658 - val_loss: 636.6118 - val_mean_absolute_error: 636.6118
Epoch 15/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 631.3273 - mean_absolute_error: 631.3273 - val_loss: 636.2238 - val_mean_absolute_error: 636.2238
Epoch 16/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 627.4358 - mean_absolute_error: 627.4358 - val_loss: 636.5825 - val_mean_absolute_error: 636.5825
Epoch 17/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 635.1760 - mean_absolute_error: 635.1760 - val_loss: 636.4169 - val_mean_absolute_error: 636.4169
Epoch 18/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - loss: 632.3535 - mean_absolute_error: 632.3535 - val_loss: 636.5175 - val_mean_absolute_error: 636.5175
Epoch 19/25
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - loss: 630.6462 - mean_absolute_error: 630.6462 - val_loss: 637.0197 - val_mean_absolute_error: 637.0197
Epoch 20/25
1209/1750 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 627.8955 - mean_absolute_error: 627.8955

KeyboardInterrupt: